repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2  # Use the ref you want to point at
    hooks:
    -   id: flake8
        exclude: migrations/
        args: ["--max-line-length=88"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812  # Use the ref you want to point at
    hooks:
    -   id: mypy
        exclude: migrations/
        args: [--config-file=mypy.ini]

-   repo: https://github.com/psf/black
    rev: 23.3.0  # replace with the actual version number
    hooks:
    -   id: black
        exclude: migrations/
