repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2  # Use the ref you want to point at
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812  # Use the ref you want to point at
    hooks:
    -   id: mypy

-   repo: https://github.com/psf/black
    rev: 21.9b0  # Use the ref you want to point at
    hooks:
    -   id: black
