"""correct_typo_on_grupo

Revision ID: 4f28e5d2e9fa
Revises: b02d77ec3942
Create Date: 2023-06-12 14:33:44.558483

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "4f28e5d2e9fa"
down_revision = "b02d77ec3942"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grupo",
        sa.Column("nome_exibicao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("grupo", "nome_exibicacao")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grupo",
        sa.Column("nome_exibicacao", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("grupo", "nome_exibicao")
    # ### end Alembic commands ###
