"""add_relationships_delete_links

Revision ID: 63e414f7d1df
Revises: bcd58980dd72
Create Date: 2023-06-26 20:03:14.640129

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '63e414f7d1df'
down_revision = 'bcd58980dd72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microprocesso', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microprocesso', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
