"""2023_06_19_microprocesso_created

Revision ID: bcd58980dd72
Revises: 51ec1a04898b
Create Date: 2023-06-19 08:52:48.848696

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bcd58980dd72'
down_revision = '51ec1a04898b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microprocesso', sa.Column('macroprocesso_id', sa.Integer(), nullable=True))
    op.drop_constraint('microprocesso_grupo_id_fkey', 'microprocesso', type_='foreignkey')
    op.create_foreign_key(None, 'microprocesso', 'macroprocesso', ['macroprocesso_id'], ['id'])
    op.drop_column('microprocesso', 'grupo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microprocesso', sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'microprocesso', type_='foreignkey')
    op.create_foreign_key('microprocesso_grupo_id_fkey', 'microprocesso', 'macroprocesso', ['grupo_id'], ['id'])
    op.drop_column('microprocesso', 'macroprocesso_id')
    # ### end Alembic commands ###
